/**
 * The expiry predicate EviteClient hands its CookieSessionManager must itself
 * call a 401 CDN/WAF refusal page NOT expired (chrischall/mcp-host#1015,
 * evite-mcp#183). The page never reached Evite, so nothing judged the session:
 * flagging it would cost a re-login (dropping the cached session) and a replay.
 * This pins the evite-side predicate directly, independent of any guard the
 * shared session manager adds on top.
 */
import { describe, it, expect, vi } from 'vitest';

type Opts = { isExpired: (res: Response) => Promise<boolean> };
const captured: Opts[] = [];

vi.mock('@chrischall/mcp-utils/session', async (orig) => {
  const real = await orig<typeof import('@chrischall/mcp-utils/session')>();
  class CapturingManager<T> extends real.CookieSessionManager<T> {
    constructor(opts: ConstructorParameters<typeof real.CookieSessionManager<T>>[0]) {
      super(opts);
      captured.push(opts as unknown as Opts);
    }
  }
  return { ...real, CookieSessionManager: CapturingManager };
});

const { EviteClient } = await import('../src/client.js');

const CLOUDFRONT_401 =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><HTML><HEAD>' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>401 ERROR</H1><H2>The request could not be satisfied.</H2>' +
  "Request blocked. We can't connect to the server for this app or website at this time." +
  '<PRE>Generated by cloudfront (CloudFront)\nRequest ID: AbCd==</PRE></BODY></HTML>';

function isExpired(): Opts['isExpired'] {
  captured.length = 0;
  new EviteClient({ resolveSession: async () => ({ cookieHeader: 'x=1' }) });
  return captured[0]!.isExpired;
}

describe('EviteClient isExpired on a 401', () => {
  it('a CloudFront 401 block page is not an expiry', async () => {
    const res = new Response(CLOUDFRONT_401, { status: 401, headers: { 'content-type': 'text/html' } });
    expect(await isExpired()(res)).toBe(false);
    // The caller's copy stays readable (the predicate reads a clone).
    expect(await res.text()).toContain('Request blocked');
  });

  it('a Cloudflare challenge (cf-mitigated) on a 401 is not an expiry', async () => {
    const res = new Response('<!DOCTYPE html><html><head><title>Just a moment...</title></head></html>', {
      status: 401,
      headers: { 'content-type': 'text/html', 'cf-mitigated': 'challenge', server: 'cloudflare' },
    });
    expect(await isExpired()(res)).toBe(false);
  });

  it('control: a genuine JSON 401 is an expiry', async () => {
    const res = new Response('{"detail":"Authentication credentials were not provided."}', { status: 401 });
    expect(await isExpired()(res)).toBe(true);
  });

  it('control: an empty 401 is an expiry', async () => {
    expect(await isExpired()(new Response('', { status: 401 }))).toBe(true);
  });
});
